// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvJDPd_rkVDDSufXRnu4t-SLj4CW8L3Y',
    appId: '1:305918132110:android:6a3585d4812f9114f3aedf',
    messagingSenderId: '305918132110',
    projectId: 'tarnobrzeg-112',
    storageBucket: 'tarnobrzeg-112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_iZqJZcvxHjpwTAw_576q2AOZvhDw64',
    appId: '1:305918132110:ios:3373af718b2ff021f3aedf',
    messagingSenderId: '305918132110',
    projectId: 'tarnobrzeg-112',
    storageBucket: 'tarnobrzeg-112.firebasestorage.app',
    iosBundleId: 'pl.tarnobrzeg112.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-G5qZmy1zT3C7Y7Tpg_9dEeZZKItChw',
    appId: '1:305918132110:web:6bc2e412bd4a76bcf3aedf',
    messagingSenderId: '305918132110',
    projectId: 'tarnobrzeg-112',
    authDomain: 'tarnobrzeg-112.firebaseapp.com',
    storageBucket: 'tarnobrzeg-112.firebasestorage.app',
    measurementId: 'G-2JXZPFWX58',
  );
}
